# Generated by Django 4.0.2 on 2022-02-12 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Entrydate', models.DateField(auto_created=True, auto_now_add=True)),
                ('empID', models.IntegerField(unique=True, verbose_name='Staff ID')),
                ('empName', models.CharField(max_length=100, verbose_name='Staff Name')),
                ('Updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('Manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('directory', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.directory')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgName', models.CharField(max_length=100, verbose_name='Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Entrydate', models.DateField(auto_created=True, auto_now_add=True)),
                ('empDocs', models.FileField(max_length=500, upload_to='media/documents', verbose_name='Documents')),
                ('empImages', models.ImageField(max_length=500, upload_to='media/images', verbose_name='Images')),
                ('RecordOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mainapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', related_query_name='tags', to='mainapp.records')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payementId', models.IntegerField(unique=True)),
                ('paydate', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('status', models.BooleanField(default=False, verbose_name='PAYEMENT STATUS')),
                ('staffinfor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.employee')),
            ],
        ),
        migrations.AddField(
            model_name='directory',
            name='parent_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.organisation'),
        ),
    ]
